---
title: "lab10"
author: "Hao Zeng"
date: "November 20, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Question 1
```{r}
cumulate_dist <- function(x,n,pai){
  p = 0
  for (i in 0:x) {
    p = p + choose(n,i)*pai^i*(1-pai)^(n-i)
  }
  return(p)
}

cumulate_dist(4,10,0.5)
pbinom(4,10,0.5)
```

# Question 2
```{r}
# Since power indicates the ability for a test to reject null hypothesis when null hypothesis is wrong and t-test assumes that data follows a normal distriution, we can generate data without nomal distribution and calculate the fraction of rejecting null hypothesis in 10,000 simulations to obtain the power.

# For exponential function, if random variable x follows exp(lambda), then the mean and standard deviation of x are both 1/lambda.

power_t <- function(n, delta, mu0, sd, sig, s){
  set.seed(123)
  k = NULL
  for (i in 1:s) {
    x <- rnorm(n, mu0, sd)
    k[i] =  t.test(x, mu = mu0 + delta, alternative = 'two.sided',conf.level = 1-sig)$p.value
  }
  return(sum(k < sig)/s)
}
power_t(30,0.5,0,1,0.05,10000)


power.t.test(n = 30, delta = 0.5, sd = 1, sig.level = 0.05, type = 'one.sample')$power
```